### ISSUE TITLE
Issues with incoming attacks not getting defended

### ISSUE THREAD

**Issue by JCalvinL** [SigmaG/Matawa#2]
I think it's the commit in: https://github.com/SigmaG/Matawa/commit/76436d78be24bfb57b79f47d46838209a3f17143

That is causing attacks to not get registered. You were definitely right about it being too buggy for public consumption. 

I also have an issue with the way how the new defense system is unable to upkeep defenses. Which is caused by a particularly strange lua error in the misc.lua file with no specified location for which line it is on.

**Comment by SigmaG** [comment]
Reverted three commits, we'll have to work on them later on.
