### ISSUE TITLE
Prompt is gagged.

### ISSUE THREAD

**Issue by JCalvinL** [SigmaG/Matawa#5]
https://dl.dropboxusercontent.com/u/55500546/MKO/promptgagged.html

This log shows that the current new prompt function feature is causing all new prompt lines to get gagged on every exit and room look. It's not until you run into something that spams a newline message twice under 0.5 seconds that it shows the prompt, but it... kinda just double shows the prompt anyways. (log is me not using the latest commit I sent)

**Comment by SigmaG** [comment]
Commit 0525d1c should solve that.

**Comment by SigmaG** [comment]
Though, it will prevent players from timeouting... I'm going to change this so that it would only be run when fishing/bashing/pvping (with the toggles or mtw.status.combat).
